---
abstract: 'restricted URI Templates handler'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::More: 0
  Test::UseAllModules: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-Template-Restrict
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  Filter::Util::Call: 0
  List::MoreUtils: 0
  URI: 0
  URI::Escape: 0
  Unicode::Normalize: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/masaki/uri-template-restrict.git
version: 0.03
