---
abstract: 'restricted URI Templates handler'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::More: 0
  ok: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-Template-Restrict
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  List::MoreUtils: 0
  Mouse: 0.14
  Regexp::Assemble: 0
  URI: 0
  URI::Escape: 0
  Unicode::Normalize: 0
  namespace::clean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
